server:
  host: "localhost"
  port: 80
  path:
    pathServer: ""
    pathOutputFile: "Controller/ascii-art/output/"
  log:
    path: "Controller/log/"
    fileName: "log.log"

link:
  home:
    urlHome: "/"
    pathHomeHtml: "Controller/assets/html/index.html"
  print:
    urlPrint: "/print"
    pathPrintHtml: "Controller/assets/html/print.html"
  output:
    urlOutput: "/output"
    pathOutputHtml: "Controller/assets/html/output.html"
  reverse:
    urlReverse: "/reverse"
    pathReverseHtml: "Controller/assets/html/reverse.html"
  downloadsFiles:
    urlDownloadsFiles: "/download/output/"
    pathDownloadsFiles: "Controller/ascii-art/output"
  loadsAssets:
    urlLoadsAssets: "/load-assets/"
    pathLoadsAssets: "./Controller/assets"
